
var auth_options = {"\
https://api.twitch.tv/kraken/oauth2/authorize	\
    ?response_type=token	\
    &client_id=qxihlu11ef6gpohfhqb9b27d40u6lj	\
    &redirect_uri=<your registered redirect URI>	\
    &scope=<space-separated list of auth scopes>	\
    &state=<your unique token generated by your application>"
};

var channel_options = {
host : "https://api.twitch.tv",
path :"/kraken/channel/ollrek",
  'Accept: application/vnd.twitchtv.v5+json',
  'Client-ID: qxihlu11ef6gpohfhqb9b27d40u6lj',
  'Authorization: OAuth cfabdegwdoklmawdzdo98xt2fo512y',
  method: 'GET'
};

var req = http.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    console.log('BODY: ' + chunk);
  });
});

req.on('error', function(e) {
  console.log('problem with request: ' + e.message);
});

// write data to request body
req.write('data\n');
req.write('data\n');
req.end();